### ISSUE TITLE
Support for Label-Based Configuration for kubernetes and docker swarm

### ISSUE THREAD

**Issue by evgenyigumnov** [evgenyigumnov/cblt#19]
Add support to read configuration from labels in Docker Swarm or Kubernetes environments. This feature should enhance deployment flexibility and simplify configuration management for containerized environments.

**Proposed Feature:**
- Introduce a command-line parameter `--labeled-config` that can accept values such as `docker_swarm` or `kubernetes`.
- Implement logic to parse and apply configuration from labels specific to the chosen orchestration platform.

**Parameters:**
1. `--labeled-config=docker_swarm`: Enables reading configuration from Docker Swarm labels.
2. `--labeled-config=kubernetes`: Enables reading configuration from Kubernetes labels.

**Additional Considerations:**
- Ensure compatibility with existing configuration methods.
- Provide detailed documentation and examples on how to set up and use label-based configuration.
- Include error handling for cases where the required labels are missing or incorrectly formatted.

**Benefits:**
- Simplifies dynamic configuration management in containerized environments.
- Aligns with industry practices of using labels for service configuration in orchestrators.

**Comment by evgenyigumnov** [comment]
```
version: '3.9'
services:
  caddy:
    image: ievkz/cblt:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app
    environment:
      CBLT_INGRESS_NETWORK: "ingress"
    ports:
      - "8080:80"
  echo:
    image: echo-spring
    networks:
      - app
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "cblt.hosts=domain.com domain.org"
        - "cblt.path=/api/"
        - "cblt.port=9000"
networks:
  app:
    external: false
```
